### ISSUE TITLE
Failed to load model class 'SigmaModel'

### ISSUE THREAD

**Issue by MAGALLANESJoseManuel** [medialab/ipysigma#233]
Failed to load model class 'SigmaModel' from module 'ipysigma'
Error: No version of module ipysigma is registered
    at f.loadClass (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.b4eddbb09f5fd50a4007.js?v=b4eddbb09f5fd50a4007:1:74934)
    at f.loadModelClass (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.9f709c2076672b1bfe2b.js?v=9f709c2076672b1bfe2b:1:10729)
    at f._make_model (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.9f709c2076672b1bfe2b.js?v=9f709c2076672b1bfe2b:1:7517)
    at f.new_model (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.9f709c2076672b1bfe2b.js?v=9f709c2076672b1bfe2b:1:5137)
    at f.handle_comm_open (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.9f709c2076672b1bfe2b.js?v=9f709c2076672b1bfe2b:1:3894)
    at _handleCommOpen (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.b4eddbb09f5fd50a4007.js?v=b4eddbb09f5fd50a4007:1:73471)
    at v._handleCommOpen (http://localhost:8888/static/notebook/3676.bundle.js:1:30809)
    at async v._handleMessage (http://localhost:8888/static/notebook/3676.bundle.js:1:32703)

**Comment by Yomguithereal** [comment]
This tends to happen with some Jupyter versions. Try relaunching everything (and clear the cell's output and cache also).

**Comment by gaardhus** [comment]
Getting same error, also in vscode and when writing with to_html. Tried clearing and relaunching and it didn't solve.

**Comment by Yomguithereal** [comment]
I have finally fixed related to the latest ipywidgets/jupyterlab breaking changes on the matter. Can you test v0.24.4 and tell me whether this addresses the problem?

**Comment by nyxpho** [comment]
Hello! I have the latest version of the library and this issue does not seem fixed:

[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'SigmaModel' from module 'ipysigma'
loadClass@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/446.bf169bd3821a9ba1aa62.js?v=bf169bd3821a9ba1aa62:1:75363
loadModelClass@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/327.8166aeb81cf1531ca240.js?v=8166aeb81cf1531ca240:1:10579
_make_model@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/327.8166aeb81cf1531ca240.js?v=8166aeb81cf1531ca240:1:7367
new_model@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/327.8166aeb81cf1531ca240.js?v=8166aeb81cf1531ca240:1:5136
handle_comm_open@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/327.8166aeb81cf1531ca240.js?v=8166aeb81cf1531ca240:1:3893
1446/v/this._handleCommOpen@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/446.bf169bd3821a9ba1aa62.js?v=bf169bd3821a9ba1aa62:1:73900
_handleCommOpen@http://localhost:8888/static/notebook/notebook_core.4799ce7e762b693682b6.js?v=4799ce7e762b693682b6:116070:19

**Comment by Yomguithereal** [comment]
Frankly Jupyter support for widgets is a hellscape and I don't really know what to do to help since I have no way to reproduce. Things you might want to try to fix the problem:

- Upgrade jupyter
- Upgrade ipywidgets
- Run `jupyter labextension list` to see if something is amiss
- Refresh your browser & jupyter's cache

**Comment by nyxpho** [comment]
Thank you for the fast answer! Clearing jupyter's cache worked!
